name: Bug report
description: Report something that isn't working correctly
labels: bug
body:
    - type: textarea
      attributes:
        label: Details
        description: Any additional info about the bug.
    - type: textarea
      attributes:
        label: Steps to reproduce
        description: If the bug isn't easily replicable, detail exactly how it can be reproduced.
    - type: textarea
      attributes:
        label: Debug information
        description: >
          Click **Copy debug info** at the bottom of the plugin settings and paste the result here. This helps narrow down any settings and conflicting plugins that may be causing your issue.
        render: shell              
      validations:
        required: true
    - type: checkboxes
      attributes:
        label: Checklist
        options:
          - label: I updated to the latest version of the plugin.
            required: true

