name: Enhancement
description: Suggest a feature for this plugin
labels: enhancement
body:
  - type: input
    attributes:
      label: Summary
      description: A clear and concise description of what you've requesting.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Details
      description: Any details, additional information, or further reasoning.
    validations:
      required: true
